### ISSUE TITLE
# F4原理图可能引用有误

### ISSUE THREAD

**Issue by wangfeng22** [yogykwan/f5jpg-edb#1]
https://github.com/yogykwan/f5jpg-edb/blob/3bc1b190713aec3600f489940d455a412f310c5b/f5.tex#L101
此处F4原理图与F3处相同，实际应为正偶数和负奇数代表消息0，负偶数和正奇数代表1。

**Comment by wangfeng22** [comment]
在PDF中看到的。

**Comment by yogykwan** [comment]
Thanks for telling me this. I've change .tex based on your advice. However, as it's been such a while, I really can't find the original images.
